
spring:
  #mysql configuration
  datasource:
    url: jdbc:mysql://localhost:3306/moneymanager
    username: root
    password: root
  #JPA configuration
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  # Email configuration
  mail:
    host: smtp-relay.brevo.com
    port: 587
    username: ${BREVO_USERNAME}
    password: ${BREVO_PASSWORD}
    properties:
      mail:
        smtp:
          from: ${BREVO_FROM_EMAIL}
          auth: true
          starttls:
            enable: true
    protocol: smtp
    # Activate profile
#  profiles:
#    active: "prod"

# JWT Configuration
# Generate a secure secret key (minimum 256 bits for HS256)
# You can generate one using: openssl rand -base64 64
jwt:
  secret: abc
  expiration: 86400000
  # JWT token expiration: 24 hours (in milliseconds)
  # Refresh token expiration: 7 days (in milliseconds)
  refresh-token:
    expiration: 604800000


# prefix of endpoints
server:
  servlet:
    context-path: /api/v1.0

money:
  manager:
    frontend:
      url: ${MONEY_MANAGER_FRONTEND_URL}

app:
  activation:
    url: ${MONEY_MANAGER_BACKEND_URL}
  email:
    name: "Money Manager App"





